/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
import java.util.Random;
public class OneOfEachStats 
{
	public static void main (String[] args) 
	{
		// Gets the two command-line arguments
		int times = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
        Random generator = new Random(seed);  
		boolean girl;
		boolean boy;
		double sum = 0;
		double num;
		int count;
		int child2 = 0;
		int child3 = 0;
		int child4 = 0;
		for(int i = 0; i < times; i++)
		{
			girl = false;
			boy = false;
			count = 0;
			while((!girl) || (!boy))
			{
				num = generator.nextDouble();
				if(num > 0.5)
				{
					boy = true; 
					count++;
				}
				else
				{
					girl = true;
					count++;
				}

			}
			sum += count;
			if (count == 2) child2++;
				else if (count == 3) child3++;
						else child4++;
				
			
		}
		double avg = (double)(sum)/times;
		String str = "";
		if ((child2 > child3) && (child2 > child4)) str = "2.";
				else if ((child3 > child2) && (child3 > child4)) str = "3.";
						else if ((child4 > child2) && (child4 > child3)) str = "4 or more.";
							else if ((child4 == child2) && (child4 != child3)) str = " 2 and 4.";
								else if ((child4 == child3) && (child4 != child2)) str = " 3 and 4.";
									else if ((child2 == child3) && (child2 != child4)) str = " 2 and 3.";
										else str = " 2, 3 and 4";

		System.out.println("Average: " + avg + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + child2);
		System.out.println("Number of families with 3 children: " + child3);
		System.out.println("Number of families with 4 or more children:: " + child4);
		System.out.println("The most common number of children is " + str);

		
	}
}
